### ISSUE TITLE
Error in Parsing Schedules: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by OberfragGER** [iobroker-community-adapters/ioBroker.doorbird#73]
Hi,

i own a new Doorbird D201x since 06/2023. So i have installed 2 instances of the Door-Adapter.

After a while, the Doorbird.1 (the new one) gives me a warning:

`Error in Parsing Schedules: RangeError: Maximum call stack size exceeded`

The adapter ist still green and everything seems to work fine.
After a restart of the adapter, everthing works good for 2-4 weeks an the the warning happens again.

Any hints?

**Comment by OberfragGER** [comment]
> Which Adapter Version?

Sorry. My specs:

`iobroker
Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
1596 MHz
Modell
Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
RAM
5 GB
System-Betriebszeit
23 T. 11:30:56
Node.js
v18.16.0 (Es gibt eine neuere Version: v18.17.1)
time
1692696320386
timeOffset
-120
Anzahl der Adapter
491
NPM
9.5.1
Datenträgergröße
7.78 GB
freier Festplattenspeicher
4.29 GB
Betriebszeit
7 T. 10:51:05
Aktive Instanzen
43
Weg
/opt/iobroker/`

Doorbird Adapter: v1.0.5

**Comment by Schmakus** [comment]
Please check the latest version 1.2.3.
If the error message appears again after a longer period of time, please report again. Thanks!

**Comment by OberfragGER** [comment]
> Please check the latest version 1.2.3. If the error message appears again after a longer period of time, please report again. Thanks!

Done!

**Comment by OberfragGER** [comment]
> Please check the latest version 1.2.3. If the error message appears again after a longer period of time, please report again. Thanks!

Ist happens today again.
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28652993/85df30e9-f282-4b95-9b5e-ab56790d1296)

Im on version 1.2.3

**Comment by OberfragGER** [comment]
> Please check the latest version 1.2.3. If the error message appears again after a longer period of time, please report again. Thanks!

I set the adapter on debug (without restart). Look- i have a lot entry about the PIN code!
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28652993/455f19c2-e058-4053-8458-58bfd7b3ad74)

On the doorbird is a keypad attached and for testing things i setup a PIN-Code (240477).
So for me this could be a hint or?

**Comment by Schmakus** [comment]
Bitte prüfen mit v1.2.4

**Comment by OberfragGER** [comment]
> Bitte prüfen mit v1.2.4

01.09.2023, 8:30 Uhr: Ist installiert. Ich melde mich falls es wieder kommt.

**Comment by Klaus-Lucas** [comment]
auch ich habe heute viele dieser Fehlermeldungen erhalten.

Admin version: 6.9.2
Adapter version: 1.2.4
JS-Controller version: 5.0.2
Node version: 18.17.1
Operating system: Ubuntu 22.04.3 LTS


`<html><body>


2023-09-08 16:40:24.552  - warn: doorbird.0 (144859) Error in Parsing Schedules: RangeError: Maximum call stack size exceeded
--
2023-09-08 16:43:24.767  - warn: doorbird.0 (144859) Error in Parsing Schedules: RangeError: Maximum call stack size exceeded


</body>
</html>`

**Comment by OberfragGER** [comment]
Ich bin mir unsicher, ob sich der Fehler von allein löst.

Hast du die Instanz seitdem neu gestartet? Bei mir scheint sich das zu fangen.

hast du irgendein „offizielles Zubehör“ dran? Also Keypad, Fingersensor o.ä.? Welche Doorbird? Ich habe die 210x

**Comment by Klaus-Lucas** [comment]
Ich habe jetzt die Instanz neu gestartet und momentan ist Ruhe. Aber der Fehler weißt ja drarauf hin, dass irgendwann der Stack überläuft, heißt es dauert eine Zeit nach einem Neustart des Adapters, bis der Fehler wieder auftritt. Schätze so 1 W. Meine Doorbird ist eine 2100.

**Comment by Schmakus** [comment]
Guten Morgen.
Der Fehler sagt, dass es zu einem Überlauf kommt. Meist, bzw. hauptsächlich in schleifen oder rekursiven Aufrufen. 
Ich konnte den Fehler noch nicht identifizieren. Ich werde ein paar debug logs einbauen müssen. 
Ich selbst habe merkwürdigerweise keine Fehler. Der Adapter läuft seit Wochen ohne Neustart. 
Ein Neustart der Adapter schaft kurzfristig Abhilfe, bei betroffenen Systemen.

**Comment by OberfragGER** [comment]
> Guten Morgen.
> Der Fehler sagt, dass es zu einem Überlauf kommt. Meist, bzw. hauptsächlich in schleifen oder rekursiven Aufrufen.
> Ich konnte den Fehler noch nicht identifizieren. Ich werde ein paar debug logs einbauen müssen.
> Ich selbst habe merkwürdigerweise keine Fehler. Der Adapter läuft seit Wochen ohne Neustart.
> Ein Neustart der Adapter schaft kurzfristig Abhilfe, bei betroffenen Systemen.

Wie gesagt. Ich habe 2 Doorbird 2100 und der Fehler tritt nur bei der Doorbird mit Keypad auf. Deshalb die Nachfrage an Klaus-Lucas da du ja meines Wissens auch kein weiteres Zubehör daran hst. Ich vermute einen Zusammenhang mit dem Keypad.

Auch bei mir läuft das immer ca. 1W.

**Comment by Klaus-Lucas** [comment]
Also ich meine Station besteht nur aus Kamera und 2 Klingeltastern. Fingerabdruckscanner hatte meine Tür schon gehabt.

**Comment by Schmakus** [comment]
> > Guten Morgen.
> 
> > Der Fehler sagt, dass es zu einem Überlauf kommt. Meist, bzw. hauptsächlich in schleifen oder rekursiven Aufrufen.
> 
> > Ich konnte den Fehler noch nicht identifizieren. Ich werde ein paar debug logs einbauen müssen.
> 
> > Ich selbst habe merkwürdigerweise keine Fehler. Der Adapter läuft seit Wochen ohne Neustart.
> 
> > Ein Neustart der Adapter schaft kurzfristig Abhilfe, bei betroffenen Systemen.
> 
> 
> 
> Wie gesagt. Ich habe 2 Doorbird 2100 und der Fehler tritt nur bei der Doorbird mit Keypad auf. Deshalb die Nachfrage an Klaus-Lucas da du ja meines Wissens auch kein weiteres Zubehör daran hst. Ich vermute einen Zusammenhang mit dem Keypad.

Kannst du bitte mal einen debug log hier Posten. Ich benötige den log nach Adapter Neustart. 
Evtl. versucht der Adapter immer wieder Zeitpläne zu erstellen, obwohl nicht nötig.
Wird dir in den Objekten irgendwas im Zusammenhang mit dem Keypad angezeigt?

**Comment by Klaus-Lucas** [comment]
Also hier wäre dann meines, wobei bei:
"Cheking if Favorite for Doorbell ID 102 exists."
das fehlende "c" noch eingebaut werden sollte.

`
--
2023-09-09 15:47:09.419  - info: host.iobroker "system.adapter.doorbird.0" enabled
2023-09-09 15:47:09.477  - info: host.iobroker instance system.adapter.doorbird.0 started with pid 1411538
2023-09-09 15:47:09.684  - debug: doorbird.0 (1411538) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-09-09 15:47:09.699  - debug: doorbird.0 (1411538) Objects client ready ... initialize now
2023-09-09 15:47:09.699  - debug: doorbird.0 (1411538) Objects create System PubSub Client
2023-09-09 15:47:09.700  - debug: doorbird.0 (1411538) Objects create User PubSub Client
2023-09-09 15:47:09.714  - debug: doorbird.0 (1411538) Objects client initialize lua scripts
2023-09-09 15:47:09.716  - debug: doorbird.0 (1411538) Objects connected to redis: 127.0.0.1:9001
2023-09-09 15:47:09.728  - debug: doorbird.0 (1411538) Redis States: Use Redis connection: 127.0.0.1:9000
2023-09-09 15:47:09.733  - debug: doorbird.0 (1411538) States create System PubSub Client
2023-09-09 15:47:09.733  - debug: doorbird.0 (1411538) States create User PubSub Client
2023-09-09 15:47:09.783  - debug: doorbird.0 (1411538) States connected to redis: 127.0.0.1:9000
2023-09-09 15:47:09.836  - info:  doorbird.0 (1411538) starting. Version 1.2.4 in  /opt/iobroker/node_modules/iobroker.doorbird, node: v18.17.1,  js-controller: 5.0.12
2023-09-09 15:47:09.857  - debug: doorbird.0 (1411538) Server gestartet auf Port 8100 und IP 192.168.178.41
2023-09-09 15:47:09.910  - debug: doorbird.0 (1411538) Authorization with User ghhnoo0001 successful!
2023-09-09 15:47:09.938  - debug: doorbird.0 (1411538) Checking favorites on DoorBird Device..
2023-09-09 15:47:09.959  - debug:  doorbird.0 (1411538) Found a Favorite that belongs to me.. (ID: '0')  ('ioBroker doorbird.0 Motion': 'http://192.168.178.41:8100/motion')
2023-09-09 15:47:09.959  - debug:  doorbird.0 (1411538) Found a Favorite that belongs to me.. (ID: '1')  ('ioBroker doorbird.0 102 Ring': 'http://192.168.178.41:8100/ring?102')
2023-09-09 15:47:09.959  - debug:  doorbird.0 (1411538) Found a Favorite that belongs to me.. (ID: '2')  ('ioBroker doorbird.0 101 Ring': 'http://192.168.178.41:8100/ring?101')
2023-09-09 15:47:09.959  - debug:  doorbird.0 (1411538) Result of Favorites:  {"101":{"ID":"2","URL":"http://192.168.178.41:8100/ring?101"},"102":{"ID":"1","URL":"http://192.168.178.41:8100/ring?102"},"Motion":{"ID":"0","URL":"http://192.168.178.41:8100/motion"}}
2023-09-09 15:47:10.006  - debug:  doorbird.0 (1411538) Following schedules found:  [{"input":"doorbell","param":"102","output":[{"event":"http","param":"1","enabled":"1","schedule":{"weekdays":[{"from":"75600","to":"75599"}]}},{"event":"notify","param":"","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}}]},{"input":"doorbell","param":"101","output":[{"event":"notify","param":"","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}},{"event":"http","param":"2","enabled":"1","schedule":{"weekdays":[{"from":"75600","to":"75599"}]}},{"event":"relay","param":"1","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}}]},{"input":"motion","param":"","output":[{"schedule":{"weekdays":[{"from":"79200","to":"79199"}]},"param":"","event":"notify"},{"event":"http","param":"0","enabled":"1","schedule":{"weekdays":[{"from":"75600","to":"75599"}]}}]},{"input":"relay","param":"1","output":[{"event":"relay","param":"ghlcty:2","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}}]},{"input":"relay","param":"2","output":[]}]
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) Looping through the Schedules..
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) Detected a Doorbell Schedule!
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) The Param of the actual Schedule is: 102
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) The Output contains 2 entries!
2023-09-09 15:47:10.006  - debug:  doorbird.0 (1411538) Entry "0" is:  {"event":"http","param":"1","enabled":"1","schedule":{"weekdays":[{"from":"75600","to":"75599"}]}}
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) Entry "1" is: {"event":"notify","param":"","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}}
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) Counted 1 Doorbells.
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) Detected a Doorbell Schedule!
2023-09-09 15:47:10.006  - debug: doorbird.0 (1411538) The Param of the actual Schedule is: 101
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) The Output contains 3 entries!
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Entry "0" is: {"event":"notify","param":"","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}}
2023-09-09 15:47:10.007  - debug:  doorbird.0 (1411538) Entry "1" is:  {"event":"http","param":"2","enabled":"1","schedule":{"weekdays":[{"from":"75600","to":"75599"}]}}
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Entry "2" is: {"event":"relay","param":"1","schedule":{"weekdays":[{"from":"79200","to":"79199"}]}}
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Counted 2 Doorbells.
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Detected Motion Schedule!
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) The Output contains 2 entries!
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Entry "0" is: {"schedule":{"weekdays":[{"from":"79200","to":"79199"}]},"param":"","event":"notify"}
2023-09-09 15:47:10.007  - debug:  doorbird.0 (1411538) Entry "1" is:  {"event":"http","param":"0","enabled":"1","schedule":{"weekdays":[{"from":"75600","to":"75599"}]}}
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Checking if we need to create any favorites..
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Cheking if Favorite for Doorbell ID 102 exists.
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Favorite for Doorbell ID 102 exists!
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Checking if we need to create any favorites..
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Cheking if Favorite for Doorbell ID 101 exists.
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Favorite for Doorbell ID 101 exists!
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Checking if we need to create any favorites..
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Favorites checked successfully. No actions needed!
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Checking if we need to create Schedules on DoorBird Device..
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Okay we dont need to create any Doorbell-Schedules..
2023-09-09 15:47:10.007  - debug: doorbird.0 (1411538) Okay we dont need to create any Doorbell-Schedules..
`

**Comment by Schmakus** [comment]
@OberfragGER Kannst du mir bitte einen debug-log posten? Danke!

**Comment by OberfragGER** [comment]
> @OberfragGER Kannst du mir bitte einen debug-log posten? Danke!

Klar. Viel kürzer mein debug Log nach start. Ich bin auf 1.2.4

`<html>
<body>


doorbird.1 | 2023-09-11 14:36:12.528 | info | starting. Version 1.2.4 (non-npm: iobroker-community-adapters/ioBroker.doorbird#38add291a78a3ba5f5206c67e0398da2ea025c84) in /opt/iobroker/node_modules/iobroker.doorbird, node: v18.17.1, js-controller: 4.0.24
-- | -- | -- | --
doorbird.1 | 2023-09-11 14:36:03.948 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
doorbird.1 | 2023-09-11 14:36:03.948 | info | terminating
doorbird.1 | 2023-09-11 14:36:03.946 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>`

**Comment by Negalein** [comment]
heute wieder Warn-Meldungen

```
Error in Parsing Schedules: RangeError: Maximum call stack size exceeded. Error-Stack: RangeError: Maximum call stack size exceeded at strEscape (/opt/iobroker/node_modules/safe-stable-stringify/index.js:29:54) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:188:16) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:256:23) at stringify (/opt/iobroker/node_modules/safe-stable-stringify/index.js:598:18) at Format.transform (/opt/iobroker/node_modules/logform/json.js:28:19) at Format.transform (/opt/iobroker/node_modules/logform/combine.js:20:24) at DerivedLogger._transform (/opt/iobroker/node_modules/winston/lib/winston/logger.js:313:29) at Transform._read (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10) at Transform._write (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83) at doWrite (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)
```

**Comment by Schmakus** [comment]
> heute wieder Warn-Meldungen
> 
> 
> 
> ```
> 
> Error in Parsing Schedules: RangeError: Maximum call stack size exceeded. Error-Stack: RangeError: Maximum call stack size exceeded at strEscape (/opt/iobroker/node_modules/safe-stable-stringify/index.js:29:54) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:188:16) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:256:23) at stringify (/opt/iobroker/node_modules/safe-stable-stringify/index.js:598:18) at Format.transform (/opt/iobroker/node_modules/logform/json.js:28:19) at Format.transform (/opt/iobroker/node_modules/logform/combine.js:20:24) at DerivedLogger._transform (/opt/iobroker/node_modules/winston/lib/winston/logger.js:313:29) at Transform._read (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10) at Transform._write (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83) at doWrite (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)
> 
> ```

Hi. Du hast auch ein Keypad?
Ich werde mal ne Beta machen mit anderer Logik. Den Link werde ich dann hier posten zum Testen.

**Comment by Negalein** [comment]
> Hi. Du hast auch ein Keypad?

Nein, kein Keypad!
Ich hab die D2102V

**Comment by OberfragGER** [comment]
@Schmakus Da ich sowieso den Logparser verwende, habe ich nun einmal "RangeError" in die Überwachung genommen (ich bekomm dann eine Telegram-Nachricht).

Bisher aber alles ruhig die letzte Zeit.

**Comment by Stefan592** [comment]
Ich habe den Fehler heute mit der aktuellen Version V1.3.0 bekommen.

System: Docker
Doorbird: 1 Station

`Error in Parsing Schedules: RangeError: Maximum call stack size exceeded. Error-Stack: RangeError: Maximum call stack size exceeded at strEscape (/opt/iobroker/node_modules/safe-stable-stringify/index.js:29:54) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:188:16) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:256:23) at stringify (/opt/iobroker/node_modules/safe-stable-stringify/index.js:598:18) at Format.transform (/opt/iobroker/node_modules/logform/json.js:28:19) at Format.transform (/opt/iobroker/node_modules/logform/combine.js:20:24) at DerivedLogger._transform (/opt/iobroker/node_modules/winston/lib/winston/logger.js:313:29) at Transform._read (/opt/iobroker/node_modules/readable-stream/lib/_stream_transform.js:177:10) at Transform._write (/opt/iobroker/node_modules/readable-stream/lib/_stream_transform.js:164:83) at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:409:139)
`

![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/14180760/bdf764bd-2975-4f91-b33a-75ccf68850a8)

**Comment by OberfragGER** [comment]
Jupp. Fehler ist bei mir auch wieder da. Version 1.3.0.
Dieses mal bei Instanz 0. Eine Normale D21xx ohne Keypad etc.

`Error in Parsing Schedules: RangeError: Maximum call stack size exceeded. Error-Stack: RangeError: Maximum call stack size exceeded at strEscape (/opt/iobroker/node_modules/safe-stable-stringify/index.js:29:54) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:188:16) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:256:23) at stringify (/opt/iobroker/node_modules/safe-stable-stringify/index.js:598:18) at Format.transform (/opt/iobroker/node_modules/logform/json.js:28:19) at Format.transform (/opt/iobroker/node_modules/logform/combine.js:20:24) at DerivedLogger._transform (/opt/iobroker/node_modules/winston/lib/winston/logger.js:313:29) at Transform._read (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10) at Transform._write (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83) at doWrite (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)`

**Comment by PeterMarkl** [comment]
Ich bekomme den Fehler leider auch alle 3 Minuten:
`2024-01-17 06:55:57.814 - warn: doorbird.1 (1747) Error in Parsing Schedules: RangeError: Maximum call stack size exceeded. Error-Stack: RangeError: Maximum call stack size exceeded
at strEscape (/opt/iobroker/node_modules/safe-stable-stringify/index.js:29:54)
at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:188:16)
at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:256:23)
at stringify (/opt/iobroker/node_modules/safe-stable-stringify/index.js:598:18)
at Format.transform (/opt/iobroker/node_modules/logform/json.js:28:19)
at Format.transform (/opt/iobroker/node_modules/logform/combine.js:20:24)
at DerivedLogger._transform (/opt/iobroker/node_modules/winston/lib/winston/logger.js:313:29)
at Transform._read (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10)
at Transform._write (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83)
at doWrite (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)`

**Comment by PEPITO82** [comment]
Ich bekomme den Fehler bei meiner D1101V auch alle drei Minuten:

`doorbird.0 | 2024-01-25 12:48:50.885 | warn | Error in Parsing Schedules: RangeError: Maximum call stack size exceeded. Error-Stack: RangeError: Maximum call stack size exceeded at strEscape (/opt/iobroker/node_modules/safe-stable-stringify/index.js:58:54) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:240:20) at stringifyFnReplacer (/opt/iobroker/node_modules/safe-stable-stringify/index.js:314:23) at stringify (/opt/iobroker/node_modules/safe-stable-stringify/index.js:659:18) at Format.transform (/opt/iobroker/node_modules/logform/json.js:28:19) at Format.transform (/opt/iobroker/node_modules/logform/combine.js:20:24) at DerivedLogger._transform (/opt/iobroker/node_modules/winston/lib/winston/logger.js:313:29) at Transform._read (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10) at Transform._write (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83) at doWrite (/opt/iobroker/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:409:139)`

**Comment by Schmakus** [comment]
please check v.1.4.1 in beta repo.

**Comment by OberfragGER** [comment]
> please check v.1.4.1 in beta repo.

Ok. Is installed now. Lets see...
Thanks a lot in advance.
